# pull official base image
FROM node:15.11.0-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

RUN npm install web3@1.3.4 @truffle/hdwallet-provider@1.4.0 @openzeppelin/contract-loader && \
    touch secret_lottery.json && mkdir build
COPY ./build ./build
COPY ./scripts/lottery_cron.js ./
CMD ["node", "lottery_cron.js"]